[package]
name = "test_detach"
version = "0.1.0"
authors = ["Ilya Bogdanov <ilya.bogdanov@xdev.re>"]
edition = "2018"

[dependencies]
jni = { path = "../jni-rs", features = ["invocation"] }
env_logger = "0.6.1"
